name: Web CI

on:
  push:
    paths:
      - 'apps/web/**'
      - '.github/workflows/web.yml'
    branches: [main]
  pull_request:
    paths:
      - 'apps/web/**'
      - '.github/workflows/web.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build 